# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-08-16 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='IsVIP',
        ),
    ]
