# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-08-16 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_userinfo_isvip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='用户名'),
        ),
    ]
